version: "3"
services:
  mongo-server:
    image: "mongo"
    restart: always
  node-app:
    restart: always
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo-server/admin
      - PORT=4000

